//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDontomate
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PERFILES
    {
        public int IDPERFIL { get; set; }
        public string NOMBRE { get; set; }
        [DataType(DataType.MultilineText)]
        public string DESCRIPCION { get; set; }
    }
}
