//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDontomate
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        public int IDPERSONA { get; set; }
        public string SEUDONIMO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string EMAIL { get; set; }
        public int IDPERFIL { get; set; }
    
        public virtual PERFILES PERFILES { get; set; }
    }
}
